### ISSUE TITLE
Error: ../Common/CUDA/TIGRE_common.cpp (14): CBCT:CUDA:Atb an illegal memory access was encountered

### ISSUE THREAD

**Issue by ecoArcGaming** [CERN/TIGRE#634]
Hi, I am using the latest TIGRE Python (finally installed after many struggles...), and when I tried to run some FDK reconstruction scripts. I encountered the following error:
`./Common/CUDA/TIGRE_common.cpp (7): Main loop fail 
../Common/CUDA/TIGRE_common.cpp (14): CBCT:CUDA:Atb an illegal memory access was encountered`

No further detail was provided by the interpreter. I tried some of the fixes in this issue: https://github.com/CERN/TIGRE/issues/501 to no avail. I am running this on 1 of the 4 A6000 GPUs on a cluster, not sure if that is relevant. How can I resolve this error? Thanks.

**Comment by AnderBiguri** [comment]
Is this the first time that happens, or are you running some ML-pipeline? 

There seems to be an issue when running ML-type things (i.e. when calling Atb/FDK thousands of times) https://github.com/CERN/TIGRE/issues/617

**Comment by ecoArcGaming** [comment]
It is a pipeline but the very first call would terminate and return this error.

**Comment by AnderBiguri** [comment]
@ecoArcGaming no it should not be an out of memory issue, TIGRE deals well with smaller GPU memories than the problem at hand. 

So you tried in various GPUs? can you tell me which ones?
Also, what is the CUDA version you are using?

Just trying to pinpoint the error

**Comment by ecoArcGaming** [comment]
> [@ecoArcGaming](https://github.com/ecoArcGaming) no it should not be an out of memory issue, TIGRE deals well with smaller GPU memories than the problem at hand.
> 
> So you tried in various GPUs? can you tell me which ones? Also, what is the CUDA version you are using?
> 
> Just trying to pinpoint the error

I tried Nvidia RTX 2080TI and A6000. Here are a few package versions: `cudatoolkit  11.6.2`, `cudnn  8.9.2.26`

**Comment by AnderBiguri** [comment]
Humm, I have access to RTX2080Ti I think, I'll try to run it with CUDA 11.6.2 in conda and see what happens, but its quite strange, there should not be any issue. 

I tend to have a custom CUDA installation, rather than the conda one, but this should not be an issue.

**Comment by ecoArcGaming** [comment]
Thanks. I tried a few things in the meantime. Calling `np.ascontiguousarray()` on all my inputs, running the python script with `CUDA_BLOCK = 1`. I also tried running (with the 2080TI and my conda env) https://github.com/CERN/TIGRE/blob/master/Python/example.py, and I got some slightly different CUDA errors:
`0: NVIDIA GeForce RTX 2080 Ti
1: NVIDIA GeForce RTX 2080 Ti
2: NVIDIA GeForce RTX 2080 Ti
3: NVIDIA GeForce RTX 2080 Ti
{'name': 'NVIDIA GeForce RTX 2080 Ti', 'devices': [0, 1, 2, 3]}
../Common/CUDA/TIGRE_common.cpp (7): Texture object creation fail 
../Common/CUDA/TIGRE_common.cpp (14): Ax:Siddon_projection invalid argument`

**Comment by AnderBiguri** [comment]
Yes, the issue in both cases will be due to something going off in texture creation, its just caught at different times. Can you post your script in minimal form (geometry, angles) so I can test it too?

**Comment by ecoArcGaming** [comment]
It is unfortunately a part of a larger project which I did not write. Would `example.py` not suffice for a minimal example for testing purposes?

**Comment by ecoArcGaming** [comment]
You mean the [501, 501, 501] in geo? Changed it to [500, 500, 500] and still have the same error.

**Comment by musetee** [comment]
I guess it could be a problem of multi-GPU setting. I can create projections by TIGRE on my own PC (windows, python 3.9.22, cuda 11.8) but not for our server with 4 GPUs. It reported the same error:
../Common/CUDA/TIGRE_common.cpp (7): Texture object creation fail 
../Common/CUDA/TIGRE_common.cpp (14): Ax:Siddon_projection invalid argument

> You mean the [501, 501, 501] in geo? Changed it to [500, 500, 500] and still have the same error.

**Comment by musetee** [comment]
> [@musetee](https://github.com/musetee) Interesting. What about with some size that is divisible by 4, like 512^3?

yes I used this geometry as in r2_gaussian project:
btw I have implemented in another server with almost the same environment(windows, python 3.9.22, cuda 11.8, torch 1.12.1) but with two GPUs, and it works with only warning
../Common/CUDA/TIGRE_common.cpp (18): Ax:Siddon_projection:GPUselect Detected one (or more) different GPUs.
 This code is not smart enough to separate the memory GPU wise if they have different computational times o
ts.
 First GPU parameters used. If the code errors you might need to change the way GPU selection is performed.

# Mode
mode: cone # X-ray source mode parallel/cone
filter: null

# System configuration
DSD: 7.0  # Distance Source Detector
DSO: 5.0  # Distance Source Origin

# Detector parameters
nDetector: # Number of pixels (Note: [v, u] not [u,v])
- 512 
- 512 
sDetector: # Size of image (not pixel)
- 4.0
- 4.0

# Image parameters
nVoxel: # Number of voxels [x, y, z]
- 256
- 256
- 256 
sVoxel: # size of volume (not voxel)
- 2.0
- 2.0
- 2.0

# Offsets
offOrigin: # Offset of image from origin
- 0 # x direction
- 0 # y direction
- 0 # z direction
offDetector: # Offset of Detector (only in two direction)
- 0 # u direction
- 0 # v direction

# Auxiliary
accuracy: 0.5 # Accuracy of FWD proj

# Angles
totalAngle: 360.0 # Total angle  (degree)
startAngle: 0.0 # Start angle (degree)

# Noise
noise: true
possion_noise: 10000  # lambda for possion
gaussian_noise: # mean and std for gaussian
- 0 # mean
- 10 # std

**Comment by AnderBiguri** [comment]
@musetee so it also fails for 4 gpus with 156^3, but works well in 2 GPUs?

Indeed this almost surely looks like a error in the logic for splitting the problem into 4 GPUs, but I don't seem to able to reproduce. 
I'll keep trying, I have access to another machine with 4GPUs soon.

**Comment by AnderBiguri** [comment]
in the meantime @ecoArcGaming can you try then limiting your use to 2 GPUs, to see if that works? you can use the GPU selection API that TIGRE comes with to just select a couple

**Comment by ecoArcGaming** [comment]
> in the meantime [@ecoArcGaming](https://github.com/ecoArcGaming) can you try then limiting your use to 2 GPUs, to see if that works? you can use the GPU selection API that TIGRE comes with to just select a couple

Sounds good. I will try that and let you know if it works.

**Comment by ecoArcGaming** [comment]
Sorry if this question is already answered in the doc (but I didn't find any), but how do I choose which GPU to use when I call `tigre.algs.fdk`? Can I pass in a GpuId?

**Comment by ecoArcGaming** [comment]
This did not work for me. I did
```
gpuids = gpu.getGpuIds('A6000')
gpuids.devices = [0]
print(gpuids) # {'name': 'A6000', 'devices': [0]}
vol = algs.fdk(projs geo, angles, gpuid = gpuids)
```
Which still gives:
```
../Common/CUDA/TIGRE_common.cpp (7): Main loop fail 
../Common/CUDA/TIGRE_common.cpp (14): CBCT:CUDA:Atb an illegal memory access was encountereds
```

**Comment by AnderBiguri** [comment]
@ecoArcGaming I wonder if this is an A6000 specific issue... I'll keep looking.

**Comment by musetee** [comment]
> > [@ecoArcGaming](https://github.com/ecoArcGaming) I wonder if this is an A6000 specific issue... I'll keep looking.
> 
> That makes sense!! We have 2 A6000s, 1 A4000 and 1 A5000 on that server (None of them works). Driver version is 555.85 The another server which works has one Quadro P5000 and one TITAN Xp, and the driver version is 461.33

my own PC has one 3090ti and it works fine

**Comment by AnderBiguri** [comment]
I have no idea honestly. I'll keep this open, but I don't know anymore what to look for/test....

**Comment by Pooryamn** [comment]
Hi @AnderBiguri,

I faced the same problem when I wanted to run `OS_PICCS.py` on a cluster with different nodes, where each node has different GPUs. After a lot of investigation, I found that it is a race condition between the Python wrapper and the C++ CUDA backend, and the solution is to use a GPU exclusively.

The final solution that worked for me was to use TIGRE's `GpuIds` utility:

```python
from tigre.utilities.gpu import GpuIds
```

Then, create a GPU object and pass it to the algorithm. In addition, set the following environment flag before running the Python script:

```bash
export CUDA_LAUNCH_BLOCKING=1
```

This forces all CUDA kernel launches to execute synchronously rather than asynchronously. So, the CPU will not execute the next line of Python or C++ code until the GPU explicitly reports that it has completely finished the current kernel.

This worked well for me. It should be mentioned, however, that it slows down the process a bit.
